Repository NASA-AMMOS/aerie-gateway, pull requests merged in 2023-07, with the labels that each got.

#32 Add environment variables document
  README.md
  docs/ENVIRONMENT.md
Labels: documentation

#28 Get user roles from database for use in JWT
  docs/ENVIRONMENT.md
  src/env.ts
  src/packages/auth/functions.ts
Labels: feature

#33 Add JWT_ALGORITHMS and JWT_EXPIRATION env vars
  docs/ENVIRONMENT.md
  src/env.ts
  src/packages/auth/functions.ts
Labels: refactor

#34 Upgrade deps to latest
  package-lock.json
  package.json
Labels: build, security

#36 Release v1.10.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#37 Rename 'admin' to 'aerie_admin' in default env
  docs/ENVIRONMENT.md
  src/env.ts
Labels: refactor

#38 Release v1.11.0
  package-lock.json
  package.json
  src/env.ts
Labels: release
