Repository NASA-AMMOS/aerie-gateway, pull requests merged in 2024-10, with the labels that each got.

#111 Release v2.21.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#109 Feature/plan import improvements
  src/packages/plan/gql.ts
  src/packages/plan/plan.ts
Labels: enhancement

#112 Feature: Upload external datasets
  package-lock.json
  package.json
  src/env.ts
  src/main.ts
  src/packages/auth/adapters/CAMAuthAdapter.ts
  src/packages/auth/adapters/NoAuthAdapter.ts
  src/packages/auth/functions.ts
  src/packages/auth/routes.ts
  src/packages/plan/gql.ts
  src/packages/plan/plan.ts
  src/types/auth.ts
  src/types/dataset.ts
  src/types/hasura.ts
  src/types/plan.ts
  src/types/time.ts
  src/util/fileParser.ts
  src/util/time.test.ts
  src/util/time.ts
Labels: publish

#113 Release v3.0.0
  package-lock.json
  package.json
  src/env.ts
Labels: release
