Repository NASA-AMMOS/aerie-gateway, pull requests merged in 2024-02, with the labels that each got.

#63 Release v2.3.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#66 Release v2.2.2
  package-lock.json
  package.json
  src/env.ts
Labels: release

#67 Release v2.4.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#64 Auth group -> Aerie role mapping
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .nvmrc
  docs/ENVIRONMENT.md
  package-lock.json
  package.json
  src/env.ts
  src/main.ts
  src/packages/auth/adapters/CAMAuthAdapter.ts
  src/packages/auth/functions.ts
  src/packages/auth/types.ts
  test/auth.test.ts
  vitest.config.ts
Labels: feature

#68 Update GH Actions to Use Node20 Versions
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci
