Repository NASA-AMMOS/aerie-gateway, pull requests merged in 2024-08, with the labels that each got.

#104 Release v2.17.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#105 Add `/version` endpoint
  src/packages/health/health.ts
Labels: feature

#106 Release v2.18.0
  package-lock.json
  package.json
  src/env.ts
Labels: release

#107 GH workflow: Publish docker image when PR is labeled 'publish'
  .github/workflows/publish.yml
  .gitignore
Labels: publish
